import type { RfxDoc, TerritoryDoc } from "@hi/shared";
import type {
  RecipientSuggestion,
  ReferralIntelligenceSnapshot,
  ReferralServiceOfferSummary,
  ReferralWorkspaceRecord,
} from "../data/exchangeRun3Gateway";

const DAY = 24 * 60 * 60 * 1_000;
const BASE = Date.UTC(2026, 5, 30, 14, 0, 0);

function timeline(
  referralId: string,
  entries: Array<[string, string, string, number]>,
) {
  return entries.map(([type, label, actorLabel, ageDays], index) => ({
    id: `${referralId}-event-${index + 1}`,
    type,
    label,
    actorLabel,
    createdAt: BASE - ageDays * DAY,
  }));
}

export const EXCHANGE_DEMO_RFX: RfxDoc[] = [
  {
    id: "demo-rfx-water",
    title: "Regional water-system controls modernization",
    description: "Controls engineering, installation, and commissioning for three public facilities.",
    status: "open",
    adminApprovalStatus: "approved",
    memberOnly: false,
    createdBy: "demo-public-authority",
    createdByName: "Tidewater Public Works Authority",
    territoryFips: "51093",
    location: "Isle of Wight County, VA",
    naicsCodes: ["541330", "238210"],
    evaluationCriteria: [],
    requestedDocuments: [],
    responseCount: 4,
    geo: { lng: -76.71, lat: 36.91, geohash: "dq9" },
    createdAt: BASE - 18 * DAY,
    dueDate: BASE + 24 * DAY,
  },
  {
    id: "demo-rfx-food",
    title: "Food-processing cold-chain assessment",
    description: "Assess refrigeration, energy, and logistics readiness for a regional producer network.",
    status: "open",
    adminApprovalStatus: "approved",
    memberOnly: false,
    createdBy: "demo-economic-partner",
    createdByName: "Coastal Economic Partnership",
    territoryFips: "51740",
    location: "Portsmouth, VA",
    naicsCodes: ["541614", "541690"],
    evaluationCriteria: [],
    requestedDocuments: [],
    responseCount: 2,
    geo: { lng: -76.3, lat: 36.84, geohash: "dq9" },
    createdAt: BASE - 11 * DAY,
    dueDate: BASE + 31 * DAY,
  },
  {
    id: "demo-rfx-workforce",
    title: "Skilled-trades workforce program partner",
    description: "Delivery partner for an employer-led industrial maintenance training cohort.",
    status: "open",
    adminApprovalStatus: "approved",
    memberOnly: false,
    createdBy: "demo-workforce-board",
    createdByName: "Western Tidewater Workforce Board",
    territoryFips: "51175",
    location: "Southampton County, VA",
    naicsCodes: ["611513"],
    evaluationCriteria: [],
    requestedDocuments: [],
    responseCount: 1,
    geo: { lng: -77.1, lat: 36.7, geohash: "dq8" },
    createdAt: BASE - 7 * DAY,
    dueDate: BASE + 40 * DAY,
  },
];

export const EXCHANGE_DEMO_TERRITORIES: TerritoryDoc[] = [
  {
    fips: "51093",
    name: "Isle of Wight County",
    state: "VA",
    status: "released",
    createdAt: BASE - 200 * DAY,
    centroid: { lng: -76.71, lat: 36.91 },
  },
  {
    fips: "51740",
    name: "Portsmouth",
    state: "VA",
    status: "released",
    createdAt: BASE - 160 * DAY,
    centroid: { lng: -76.3, lat: 36.84 },
  },
  {
    fips: "51175",
    name: "Southampton County",
    state: "VA",
    status: "scheduled",
    releaseDate: BASE + 45 * DAY,
    createdAt: BASE - 40 * DAY,
    centroid: { lng: -77.1, lat: 36.7 },
  },
];

export const EXCHANGE_DEMO_SERVICE_OFFERS: ReferralServiceOfferSummary[] = [
  {
    id: "demo-offer-controls",
    version: 3,
    providerLabel: "Blue Heron Controls",
    serviceName: "Industrial controls engineering",
    serviceCategory: "Engineering services",
    naicsCodes: ["541330", "238210"],
    territoryFips: ["51093", "51740"],
    acceptingReferrals: true,
    compensationType: "percentage",
    currency: "USD",
    compensationLabel: "10% of the first collected invoice",
    effectiveAt: BASE - 90 * DAY,
  },
  {
    id: "demo-offer-workforce",
    version: 1,
    providerLabel: "Hampton Roads Trades Collaborative",
    serviceName: "Employer training program design",
    serviceCategory: "Workforce development",
    naicsCodes: ["611513"],
    territoryFips: ["51093", "51175"],
    acceptingReferrals: true,
    compensationType: "none",
    currency: "USD",
    compensationLabel: "No compensation",
    effectiveAt: BASE - 30 * DAY,
  },
  {
    id: "demo-offer-energy",
    version: 2,
    providerLabel: "Commonwealth Energy Advisors",
    serviceName: "Facility energy assessment",
    serviceCategory: "Energy consulting",
    naicsCodes: ["541690"],
    territoryFips: ["51740"],
    acceptingReferrals: true,
    compensationType: "benefit",
    currency: "USD",
    compensationLabel: "Co-marketing credit; no cash value",
    effectiveAt: BASE - 60 * DAY,
  },
];

export const EXCHANGE_DEMO_REFERRALS: ReferralWorkspaceRecord[] = [
  {
    id: "demo-ref-draft",
    direction: "sent",
    status: "draft",
    activeDispute: false,
    referralType: "service_need",
    title: "Industrial safety training need",
    needSummary: "A local manufacturer needs an OSHA-aligned supervisor training cohort.",
    category: "Workforce development",
    naicsCodes: ["611513"],
    territoryFips: "51175",
    territoryLabel: "Southampton County, VA",
    referrerLabel: "Tidewater Manufacturing Alliance",
    recipientLabel: "Recipient not selected",
    actingOrganizationLabel: "Tidewater Manufacturing Alliance",
    createdAt: BASE - DAY,
    updatedAt: BASE - DAY,
    version: 0,
    consentStatus: "not_required",
    contactDisclosure: "not_applicable",
    compensation: {
      type: "none",
      label: "No compensation",
      configured: false,
      currency: "USD",
      settlementEnabled: false,
    },
    commerceStatus: "none",
    linkedEntities: [],
    timeline: timeline("demo-ref-draft", [["draft_created", "Draft created", "Demo member", 1]]),
    notes: [],
    evidenceCount: 0,
  },
  {
    id: "demo-ref-sent-rfx",
    direction: "sent",
    status: "sent",
    activeDispute: false,
    referralType: "project_opportunity",
    title: "Controls partner for water modernization",
    needSummary: "Introduce a controls specialist for the regional modernization RFx.",
    category: "Engineering services",
    naicsCodes: ["541330", "238210"],
    territoryFips: "51093",
    territoryLabel: "Isle of Wight County, VA",
    referrerLabel: "Tidewater Manufacturing Alliance",
    recipientLabel: "Blue Heron Controls",
    actingOrganizationLabel: "Tidewater Manufacturing Alliance",
    createdAt: BASE - 10 * DAY,
    updatedAt: BASE - 9 * DAY,
    version: 2,
    consentStatus: "pending",
    contactDisclosure: "withheld",
    compensation: {
      type: "percentage",
      label: "10% of first collected invoice",
      configured: true,
      currency: "USD",
      settlementEnabled: false,
    },
    commerceStatus: "none",
    serviceOfferId: "demo-offer-controls",
    serviceOfferVersion: 3,
    linkedEntities: [
      { type: "rfx", id: "demo-rfx-water", label: "Water-system controls modernization", available: true },
      { type: "team", id: "demo-team-water", label: "Water modernization response team", available: true },
    ],
    timeline: timeline("demo-ref-sent-rfx", [
      ["draft_created", "Draft created", "Demo member", 10],
      ["consent_pending", "Customer consent requested", "Demo member", 10],
      ["referral_sent", "Referral sent", "Demo member", 9],
      ["recipient_viewed", "Recipient viewed referral", "Blue Heron Controls", 8],
    ]),
    notes: [{ id: "note-water", authorLabel: "Demo member", body: "Confirm commissioning availability before the RFx briefing.", createdAt: BASE - 9 * DAY }],
    evidenceCount: 1,
  },
  {
    id: "demo-ref-received",
    direction: "received",
    status: "sent",
    activeDispute: false,
    referralType: "customer_introduction",
    title: "Cold-storage efficiency assessment",
    needSummary: "A regional producer is seeking an energy and refrigeration assessment.",
    category: "Energy consulting",
    naicsCodes: ["541690"],
    territoryFips: "51740",
    territoryLabel: "Portsmouth, VA",
    referrerLabel: "Coastal Economic Partnership",
    recipientLabel: "Commonwealth Energy Advisors",
    actingOrganizationLabel: "Commonwealth Energy Advisors",
    createdAt: BASE - 5 * DAY,
    updatedAt: BASE - 4 * DAY,
    version: 1,
    consentStatus: "confirmed",
    contactDisclosure: "available",
    contactSummary: "Synthetic customer contact is available to the authorized recipient.",
    compensation: {
      type: "benefit",
      label: "Co-marketing credit; no cash value",
      configured: true,
      currency: "USD",
      settlementEnabled: false,
    },
    commerceStatus: "none",
    serviceOfferId: "demo-offer-energy",
    serviceOfferVersion: 2,
    linkedEntities: [{ type: "rfx", id: "demo-rfx-food", label: "Cold-chain assessment RFx", available: true }],
    timeline: timeline("demo-ref-received", [
      ["draft_created", "Draft created", "Coastal Economic Partnership", 5],
      ["consent_confirmed", "Customer consent confirmed", "Coastal Economic Partnership", 5],
      ["referral_sent", "Referral sent", "Coastal Economic Partnership", 4],
    ]),
    notes: [],
    evidenceCount: 0,
  },
  {
    id: "demo-ref-accepted",
    direction: "received",
    status: "accepted",
    activeDispute: false,
    referralType: "business_lead",
    title: "Plant controls upgrade planning",
    needSummary: "Plan a phased upgrade for aging PLC and SCADA infrastructure.",
    category: "Engineering services",
    naicsCodes: ["541330"],
    territoryFips: "51093",
    territoryLabel: "Isle of Wight County, VA",
    referrerLabel: "Coastal Economic Partnership",
    recipientLabel: "Blue Heron Controls",
    actingOrganizationLabel: "Blue Heron Controls",
    createdAt: BASE - 32 * DAY,
    updatedAt: BASE - 29 * DAY,
    version: 4,
    consentStatus: "confirmed",
    contactDisclosure: "available",
    contactSummary: "Synthetic business contact disclosed after recorded consent.",
    compensation: {
      type: "percentage",
      label: "10% of first collected invoice",
      configured: true,
      currency: "USD",
      settlementEnabled: false,
    },
    commerceStatus: "awaiting_transaction",
    termsSnapshot: {
      serviceOfferId: "demo-offer-controls",
      serviceOfferVersion: 3,
      compensationType: "percentage",
      compensationLabel: "10% of the first collected invoice",
      currency: "USD",
      attributionWindowDays: 90,
      platformFeeBasisPoints: 100,
      platformFeeConfigVersion: 1,
      acceptedByLabel: "Blue Heron Controls",
      acceptedAt: BASE - 29 * DAY,
      calculationVersion: 1,
    },
    linkedEntities: [],
    timeline: timeline("demo-ref-accepted", [
      ["referral_sent", "Referral sent", "Coastal Economic Partnership", 32],
      ["recipient_viewed", "Recipient viewed referral", "Blue Heron Controls", 31],
      ["terms_locked", "Referral terms locked", "System", 29],
      ["referral_accepted", "Referral accepted", "Blue Heron Controls", 29],
    ]),
    notes: [],
    evidenceCount: 0,
  },
  {
    id: "demo-ref-converted-none",
    direction: "sent",
    status: "converted",
    activeDispute: false,
    referralType: "partner_introduction",
    title: "Workforce curriculum collaboration",
    needSummary: "Connect an employer group with a trades curriculum partner.",
    category: "Workforce development",
    naicsCodes: ["611513"],
    territoryFips: "51175",
    territoryLabel: "Southampton County, VA",
    referrerLabel: "Tidewater Manufacturing Alliance",
    recipientLabel: "Hampton Roads Trades Collaborative",
    actingOrganizationLabel: "Tidewater Manufacturing Alliance",
    createdAt: BASE - 120 * DAY,
    updatedAt: BASE - 22 * DAY,
    version: 7,
    consentStatus: "not_required",
    contactDisclosure: "not_applicable",
    compensation: {
      type: "none",
      label: "No compensation",
      configured: false,
      currency: "USD",
      settlementEnabled: false,
    },
    commerceStatus: "none",
    linkedEntities: [
      { type: "team", id: "demo-team-workforce", label: "Industrial maintenance training team", available: true },
      { type: "resource_program", id: "future-program", label: "Regional workforce grant", available: false },
    ],
    timeline: timeline("demo-ref-converted-none", [
      ["referral_sent", "Referral sent", "Demo member", 120],
      ["referral_accepted", "Referral accepted", "Trades Collaborative", 118],
      ["progress_changed", "Work began", "Trades Collaborative", 102],
      ["referral_converted", "Referral converted", "Trades Collaborative", 22],
    ]),
    notes: [],
    evidenceCount: 0,
  },
  {
    id: "demo-ref-converted-paid",
    direction: "received",
    status: "converted",
    activeDispute: false,
    referralType: "customer_introduction",
    title: "Controls commissioning engagement",
    needSummary: "Commission a completed controls installation for a synthetic regional customer.",
    category: "Engineering services",
    naicsCodes: ["541330"],
    territoryFips: "51093",
    territoryLabel: "Isle of Wight County, VA",
    referrerLabel: "Coastal Economic Partnership",
    recipientLabel: "Blue Heron Controls",
    actingOrganizationLabel: "Blue Heron Controls",
    createdAt: BASE - 150 * DAY,
    updatedAt: BASE - 12 * DAY,
    version: 10,
    consentStatus: "confirmed",
    contactDisclosure: "available",
    contactSummary: "Synthetic customer contact disclosed after recorded consent.",
    compensation: {
      type: "percentage",
      label: "10% of first collected invoice",
      configured: true,
      currency: "USD",
      grossReferralPayoutCents: 100_000,
      platformFeeBasisPoints: 100,
      platformFeeCents: 1_000,
      netReferrerPayoutCents: 99_000,
      settlementEnabled: false,
    },
    commerceStatus: "settlement_unavailable",
    termsSnapshot: {
      serviceOfferId: "demo-offer-controls",
      serviceOfferVersion: 3,
      compensationType: "percentage",
      compensationLabel: "10% of the first collected invoice",
      currency: "USD",
      attributionWindowDays: 90,
      platformFeeBasisPoints: 100,
      platformFeeConfigVersion: 1,
      acceptedByLabel: "Blue Heron Controls",
      acceptedAt: BASE - 145 * DAY,
      calculationVersion: 1,
    },
    linkedEntities: [{ type: "rfx", id: "demo-rfx-water", label: "Water-system controls modernization", available: true }],
    timeline: timeline("demo-ref-converted-paid", [
      ["referral_sent", "Referral sent", "Coastal Economic Partnership", 150],
      ["terms_locked", "Referral terms locked", "System", 145],
      ["referral_accepted", "Referral accepted", "Blue Heron Controls", 145],
      ["referral_converted", "Referral converted", "Blue Heron Controls", 20],
      ["transaction_reported", "Transaction reported", "Blue Heron Controls", 18],
      ["transaction_confirmed", "Transaction confirmed", "Coastal Economic Partnership", 14],
      ["calculation_completed", "Compensation calculated", "System", 12],
    ]),
    notes: [],
    evidenceCount: 2,
  },
  {
    id: "demo-ref-disputed",
    direction: "sent",
    status: "converted",
    activeDispute: true,
    referralType: "business_lead",
    title: "Warehouse automation assessment",
    needSummary: "Assess automation readiness for a synthetic distribution facility.",
    category: "Engineering services",
    naicsCodes: ["541330"],
    territoryFips: "51740",
    territoryLabel: "Portsmouth, VA",
    referrerLabel: "Tidewater Manufacturing Alliance",
    recipientLabel: "Blue Heron Controls",
    actingOrganizationLabel: "Tidewater Manufacturing Alliance",
    createdAt: BASE - 80 * DAY,
    updatedAt: BASE - 2 * DAY,
    version: 9,
    consentStatus: "confirmed",
    contactDisclosure: "available",
    compensation: {
      type: "fixed",
      label: "$500 fixed referral compensation",
      configured: true,
      currency: "USD",
      grossReferralPayoutCents: 50_000,
      platformFeeBasisPoints: 100,
      platformFeeCents: 500,
      netReferrerPayoutCents: 49_500,
      settlementEnabled: false,
    },
    commerceStatus: "disputed",
    linkedEntities: [],
    timeline: timeline("demo-ref-disputed", [
      ["referral_sent", "Referral sent", "Demo member", 80],
      ["referral_accepted", "Referral accepted", "Blue Heron Controls", 76],
      ["referral_converted", "Referral converted", "Blue Heron Controls", 8],
      ["dispute_opened", "Clarification requested", "Demo member", 2],
    ]),
    notes: [],
    evidenceCount: 1,
  },
  {
    id: "demo-ref-closed",
    direction: "received",
    status: "closed",
    activeDispute: false,
    referralType: "service_need",
    title: "Packaging-line maintenance support",
    needSummary: "A short-term maintenance need that was not a fit for the recipient.",
    category: "Industrial maintenance",
    naicsCodes: ["811310"],
    territoryFips: "51093",
    territoryLabel: "Isle of Wight County, VA",
    referrerLabel: "Coastal Economic Partnership",
    recipientLabel: "Blue Heron Controls",
    createdAt: BASE - 70 * DAY,
    updatedAt: BASE - 60 * DAY,
    version: 4,
    consentStatus: "confirmed",
    contactDisclosure: "available",
    compensation: {
      type: "none",
      label: "No compensation",
      configured: false,
      currency: "USD",
      settlementEnabled: false,
    },
    commerceStatus: "none",
    linkedEntities: [],
    timeline: timeline("demo-ref-closed", [
      ["referral_sent", "Referral sent", "Coastal Economic Partnership", 70],
      ["referral_accepted", "Referral accepted", "Blue Heron Controls", 68],
      ["referral_closed", "Closed — not a fit", "Blue Heron Controls", 60],
    ]),
    notes: [],
    evidenceCount: 0,
  },
];

export const EXCHANGE_DEMO_SUGGESTIONS: RecipientSuggestion[] = [
  {
    id: "demo-suggestion-controls",
    providerOrgId: "demo-org-controls",
    providerLabel: "Blue Heron Controls",
    score: 92,
    matchedCapabilities: ["Controls engineering", "SCADA commissioning"],
    territoryExplanation: "Serves released territories 51093 and 51740.",
    relationshipState: "trusted",
    acceptingReferrals: true,
    compensationConfigured: true,
    serviceOffer: EXCHANGE_DEMO_SERVICE_OFFERS[0],
    reasons: ["NAICS 541330 match", "Verified controls capability", "Established response history"],
  },
  {
    id: "demo-suggestion-workforce",
    providerOrgId: "demo-org-workforce",
    providerLabel: "Hampton Roads Trades Collaborative",
    score: 86,
    matchedCapabilities: ["Industrial maintenance training", "Employer cohort design"],
    territoryExplanation: "Serves the scheduled Southampton County territory.",
    relationshipState: "established",
    acceptingReferrals: true,
    compensationConfigured: false,
    serviceOffer: EXCHANGE_DEMO_SERVICE_OFFERS[1],
    reasons: ["NAICS 611513 match", "Territory coverage", "Prior confirmed conversion"],
  },
  {
    id: "demo-suggestion-energy",
    providerOrgId: "demo-org-energy",
    providerLabel: "Commonwealth Energy Advisors",
    score: 79,
    matchedCapabilities: ["Facility energy assessment"],
    territoryExplanation: "Published service coverage includes Portsmouth.",
    relationshipState: "new",
    acceptingReferrals: true,
    compensationConfigured: true,
    serviceOffer: EXCHANGE_DEMO_SERVICE_OFFERS[2],
    reasons: ["NAICS 541690 match", "Verified certification", "Accepting referrals"],
  },
];

export const EXCHANGE_DEMO_INTELLIGENCE: ReferralIntelligenceSnapshot = {
  generatedAt: BASE,
  windowLabel: "Trailing 12 months",
  calculationVersion: 1,
  privacyThreshold: 5,
  scopeLabel: "Tidewater Manufacturing Alliance — authorized organization activity",
  networkMetrics: [
    { id: "partners", label: "Unique partners", value: "12", detail: "Distinct authorized business-referral partners", sampleSize: 34 },
    { id: "acceptance", label: "Acceptance rate", value: "76%", detail: "26 accepted of 34 sent referrals", sampleSize: 34 },
    { id: "conversion", label: "Confirmed conversion rate", value: "35%", detail: "9 confirmed conversions of 26 accepted referrals", sampleSize: 26 },
    { id: "response", label: "Median response", value: "18h", detail: "Median time to accept or decline", sampleSize: 29 },
    { id: "repeat", label: "Repeat partner rate", value: "58%", detail: "Partners with more than one valid referral", sampleSize: 12 },
    { id: "trusted", label: "Trusted relationships", value: "3", detail: "Explainable classifications meeting minimum samples", sampleSize: 12 },
  ],
  relationships: [
    {
      id: "demo-relationship-controls",
      partnerLabel: "Blue Heron Controls",
      state: "trusted",
      acceptedReferrals: 8,
      confirmedConversions: 5,
      medianResponseHours: 11,
      disputes: 0,
      relationshipDays: 420,
      sampleSize: 8,
      factors: ["5 confirmed conversions", "11-hour median response", "No lost disputes", "420-day relationship"],
      explanation: "Trusted describes a demonstrated referral pattern; it is not a guarantee, credit rating, or payout entitlement.",
    },
    {
      id: "demo-relationship-workforce",
      partnerLabel: "Hampton Roads Trades Collaborative",
      state: "established",
      acceptedReferrals: 5,
      confirmedConversions: 2,
      medianResponseHours: 22,
      disputes: 0,
      relationshipDays: 250,
      sampleSize: 5,
      factors: ["5 accepted referrals", "2 confirmed conversions", "250-day relationship"],
      explanation: "Established reflects verified history above the five-referral minimum sample.",
    },
    {
      id: "demo-relationship-energy",
      partnerLabel: "Commonwealth Energy Advisors",
      state: "active",
      acceptedReferrals: 3,
      confirmedConversions: 1,
      medianResponseHours: 30,
      disputes: 0,
      relationshipDays: 95,
      sampleSize: 3,
      factors: ["3 accepted referrals", "Below the five-referral classification sample"],
      explanation: "Active is shown because the sample is too small for an established or trusted classification.",
    },
  ],
  industryGaps: [
    {
      id: "demo-gap-industry-maintenance",
      dimension: "industry",
      label: "Industrial maintenance (NAICS 811310)",
      demandCount: 14,
      activeRecipientCount: 3,
      unansweredDemand: 7,
      conversionRate: 21,
      suppressed: false,
      explanation: "Demand exceeds the number of currently accepting, published recipients.",
    },
    {
      id: "demo-gap-industry-cyber",
      dimension: "industry",
      label: "Cybersecurity services",
      demandCount: 4,
      activeRecipientCount: 2,
      unansweredDemand: 0,
      suppressed: true,
      explanation: "Combined into a privacy-safe small-sample group because fewer than five records qualify.",
    },
  ],
  territoryGaps: [
    {
      id: "demo-gap-territory-southampton",
      dimension: "territory",
      label: "Southampton County, VA (scheduled)",
      demandCount: 11,
      activeRecipientCount: 2,
      unansweredDemand: 6,
      conversionRate: 18,
      suppressed: false,
      explanation: "Developing demand is visible before release; scheduled status does not enable transactions.",
    },
    {
      id: "demo-gap-territory-portsmouth",
      dimension: "territory",
      label: "Portsmouth, VA",
      demandCount: 9,
      activeRecipientCount: 7,
      unansweredDemand: 1,
      conversionRate: 44,
      suppressed: false,
      explanation: "Recipient coverage currently keeps pace with confirmed referral demand.",
    },
  ],
  reciprocalPatterns: [
    {
      id: "demo-reciprocal-normal",
      partnerLabel: "Blue Heron Controls",
      classification: "normal_reciprocity",
      referralsEachDirection: "6 sent / 4 received",
      sampleSize: 10,
      notice: "Reciprocity is normal business-network activity and is not evidence of wrongdoing.",
      factors: ["Multiple external partners", "Varied referral timing", "No confirmed reversals"],
    },
    {
      id: "demo-reciprocal-review",
      partnerLabel: "Synthetic Logistics Partner",
      classification: "review_recommended",
      referralsEachDirection: "7 sent / 7 received",
      sampleSize: 14,
      notice: "Additional verification may be required. No public fraud conclusion is made.",
      factors: ["Concentrated pair activity", "Repeated same-week referrals", "Administrative review only"],
    },
  ],
  economicImpact: {
    referralsInitiated: 34,
    referralsAccepted: 26,
    confirmedConversions: 9,
    businessesConnected: 18,
    newRelationshipsFormed: 7,
    industriesConnected: 6,
    territoriesConnected: 3,
    nonCashBenefits: 2,
    rfxOpportunitiesLinked: 5,
    teamsLinked: 3,
    currencies: [
      {
        currency: "USD",
        reportedTransactionValueCents: 48_500_000,
        confirmedTransactionValueCents: 31_200_000,
        grossReferralPayoutCents: 2_410_000,
        platformFeeCents: 24_100,
        netReferrerBenefitCents: 2_385_900,
      },
    ],
  },
  notices: [
    "Reported and confirmed values are shown separately.",
    "Small aggregate cells are suppressed below five qualifying records or organizations.",
    "No cross-currency conversion or regional economic multiplier is applied.",
    "Platform membership invitations are excluded from every metric.",
  ],
};

export function cloneDemoReferrals(): ReferralWorkspaceRecord[] {
  return structuredClone(EXCHANGE_DEMO_REFERRALS);
}
