"use client";

import dynamic from "next/dynamic";
import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowRight, Building2, Check, Crown, MapPin, Network, ShieldCheck, Users } from "lucide-react";
import { AppShell } from "@/components/AppShell";
import { PublicSiteGate } from "@/components/PublicSiteGate";
import { exchangeGetFounderAvailabilityFn } from "@/lib/functions";

const MapComponent = dynamic(() => import("@/components/MapComponent").then((module) => module.MapComponent), { ssr: false, loading: () => <div className="h-72 animate-pulse rounded-3xl bg-slate-100" /> });

export default function FoundingCampaignPage() {
  const [availability, setAvailability] = useState<{ claimed: number; remaining: number; limit: number } | null>(null);
  useEffect(() => { exchangeGetFounderAvailabilityFn({}).then((result) => setAvailability(result.data)).catch(() => setAvailability(null)); }, []);
  return (
    <PublicSiteGate><AppShell><main className="overflow-hidden bg-white">
      <section className="relative bg-slate-950 px-5 py-20 text-white sm:py-28"><div className="absolute inset-0 bg-[radial-gradient(circle_at_20%_20%,rgba(16,185,129,.22),transparent_35%),radial-gradient(circle_at_80%_70%,rgba(99,102,241,.2),transparent_35%)]" /><div className="relative mx-auto max-w-6xl"><div className="max-w-4xl"><div className="inline-flex items-center gap-2 rounded-full border border-emerald-400/30 bg-emerald-400/10 px-3 py-1 text-xs font-bold uppercase tracking-widest text-emerald-300"><Crown className="h-3.5 w-3.5" /> Founding cohort</div><h1 className="mt-6 text-4xl font-black tracking-tight sm:text-6xl lg:text-7xl">Help build the business Exchange you want to use.</h1><p className="mt-6 max-w-3xl text-lg leading-relaxed text-slate-300 sm:text-xl">Joining the Exchange is free. Founding Membership is available to the first 250 verified organizations that want greater access, visibility, monthly credits, and a permanent place in the Exchange&apos;s founding cohort.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/exchange/onboarding" className="inline-flex items-center justify-center gap-2 rounded-full bg-emerald-500 px-6 py-3 font-bold text-slate-950 hover:bg-emerald-400">Find or Claim Your Business <ArrowRight className="h-4 w-4" /></Link><Link href="/register" className="inline-flex items-center justify-center rounded-full border border-slate-600 px-6 py-3 font-bold text-white hover:bg-white/5">Join the Exchange Free</Link></div></div></div></section>

      <section className="border-b border-slate-200 bg-slate-50 px-5 py-8"><div className="mx-auto grid max-w-6xl gap-5 sm:grid-cols-3"><Stat label="Founding price" value="$49/month" /><Stat label="Included after each paid invoice" value="25 credits" /><Stat label="Founding cohort" value={availability ? `${availability.claimed} of ${availability.limit} claimed` : "Live count loading"} detail={availability ? `${availability.remaining} remaining` : "Authoritative count from membership data"} /></div></section>

      <section className="mx-auto grid max-w-6xl gap-10 px-5 py-20 lg:grid-cols-2 lg:items-center"><div><Eyebrow icon={Network}>The Hi-Coworking Exchange</Eyebrow><h2 className="mt-4 text-3xl font-bold tracking-tight text-slate-950 sm:text-4xl">A local-first network for organizations that need opportunity, partners, and practical resources.</h2><p className="mt-5 leading-relaxed text-slate-600">The Exchange connects small businesses, independent professionals, public-sector suppliers, economic-development partners, and growing teams. The current platform includes organization profiles, map and directory discovery, RFx activity, referrals, teaming foundations, and resource programs at varying stages of availability.</p><div className="mt-6 grid grid-cols-2 gap-3 text-sm text-slate-700"><Mini icon={Building2} text="Small businesses" /><Mini icon={Users} text="Independent experts" /><Mini icon={ShieldCheck} text="Procurement suppliers" /><Mini icon={MapPin} text="Local ecosystem partners" /></div></div><div className="rounded-3xl bg-slate-50 p-3 ring-1 ring-slate-200"><MapComponent /></div></section>

      <section className="bg-slate-50 px-5 py-20"><div className="mx-auto max-w-6xl"><div className="mx-auto max-w-3xl text-center"><h2 className="text-3xl font-bold tracking-tight text-slate-950 sm:text-4xl">Free is the front door. Founding is a deeper commitment.</h2><p className="mt-4 text-slate-600">Both plans belong to the organization and require appropriate organization authority.</p></div><div className="mt-10 grid gap-6 lg:grid-cols-2"><Card title="Free Exchange Membership" features={["Maintain an eligible organization profile", "Browse public directory, map, opportunity, RFx, referral, teaming, and resource activity your permissions allow", "Receive and respond to permitted activity", "Upgrade later while founder capacity remains"]} cta={<Link href="/register" className="block rounded-full border border-slate-300 px-5 py-3 text-center font-bold text-slate-800">Join the Exchange Free</Link>} /><Card featured title="Founding Membership · $49/month" features={["25 business-use credits after each successfully paid monthly invoice", "Unique founder number and badge after authoritative activation", "Protected $49 rate while the qualifying subscription remains continuously active", "Founder analytics and enhanced visibility hooks as the platform expands"]} cta={<Link href="/exchange/onboarding" className="block rounded-full bg-emerald-600 px-5 py-3 text-center font-bold text-white">Become a Founding Member</Link>} /></div><p className="mt-6 text-center text-xs text-slate-500">Some advanced Exchange actions remain in staged rollout. Credits expire 12 months after grant, are non-transferable, have no cash value, and are restricted to organizational use.</p></div></section>

      <section className="mx-auto max-w-4xl px-5 py-20"><h2 className="text-center text-3xl font-bold text-slate-950">How profile claiming works</h2><div className="mt-10 grid gap-5 sm:grid-cols-3"><Step n="1" title="Search" body="We check seeded Exchange records and server-side USAspending recipient results, then merge likely duplicates." /><Step n="2" title="Claim or create" body="Request a claim for an existing unclaimed listing, or create a new organization after reviewing duplicate warnings." /><Step n="3" title="Verify authority" body="Only an owner, organization administrator, or platform administrator can purchase for the organization." /></div></section>

      <section className="bg-slate-950 px-5 py-20 text-white"><div className="mx-auto max-w-4xl"><h2 className="text-center text-3xl font-bold">Frequently asked questions</h2><div className="mt-8 divide-y divide-slate-800">{[
        ["Does payment verify my business?", "No. Payment and business verification are separate. Membership activates from verified Stripe events; organization verification follows its own review process."],
        ["Who owns the membership?", "The organization owns the Founding Membership. Authorized users manage it on the organization's behalf."],
        ["When is the founder number assigned?", "Only after an authoritative Stripe subscription event confirms activation. A browser redirect never assigns a number."],
        ["What happens if all 250 slots are taken?", "The server blocks additional checkout attempts. Temporary checkout reservations expire so abandoned sessions do not permanently consume capacity."],
        ["What can credits be used for?", "Credits support eligible Exchange business actions as those actions become available. They are not cash, stored value, gift cards, or transferable currency."],
      ].map(([question, answer]) => <details key={question} className="group py-5"><summary className="cursor-pointer list-none font-bold text-slate-100">{question}</summary><p className="mt-3 leading-relaxed text-slate-400">{answer}</p></details>)}</div><div className="mt-10 text-center"><Link href="/exchange/onboarding" className="inline-flex items-center gap-2 rounded-full bg-emerald-500 px-7 py-3 font-bold text-slate-950">Find or Claim Your Business <ArrowRight className="h-4 w-4" /></Link></div></div></section>
    </main></AppShell></PublicSiteGate>
  );
}

function Eyebrow({ icon: Icon, children }: { icon: typeof Network; children: React.ReactNode }) { return <div className="flex items-center gap-2 text-sm font-bold uppercase tracking-widest text-emerald-700"><Icon className="h-4 w-4" />{children}</div>; }
function Stat({ label, value, detail }: { label: string; value: string; detail?: string }) { return <div className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><div className="text-xs font-bold uppercase tracking-wide text-slate-400">{label}</div><div className="mt-2 text-2xl font-black text-slate-950">{value}</div>{detail && <div className="mt-1 text-xs text-slate-500">{detail}</div>}</div>; }
function Mini({ icon: Icon, text }: { icon: typeof Building2; text: string }) { return <div className="flex items-center gap-2 rounded-xl bg-slate-50 p-3"><Icon className="h-4 w-4 text-emerald-600" />{text}</div>; }
function Card({ title, features, cta, featured = false }: { title: string; features: string[]; cta: React.ReactNode; featured?: boolean }) { return <div className={`flex flex-col rounded-3xl bg-white p-7 shadow-sm ${featured ? "ring-2 ring-emerald-500" : "ring-1 ring-slate-200"}`}><h3 className="text-xl font-bold text-slate-950">{title}</h3><ul className="my-6 flex-1 space-y-3">{features.map((feature) => <li key={feature} className="flex gap-3 text-sm leading-relaxed text-slate-600"><Check className="mt-0.5 h-4 w-4 shrink-0 text-emerald-600" />{feature}</li>)}</ul>{cta}</div>; }
function Step({ n, title, body }: { n: string; title: string; body: string }) { return <div className="rounded-2xl border border-slate-200 p-5"><div className="flex h-8 w-8 items-center justify-center rounded-full bg-slate-950 text-sm font-bold text-white">{n}</div><h3 className="mt-4 font-bold text-slate-950">{title}</h3><p className="mt-2 text-sm leading-relaxed text-slate-600">{body}</p></div>; }
